// دانشگاه=دانشکده=رعسی دانکده=اسم رعیسو اظلاعاتو شماره اتاق = رشته های دانشکده ها =هر رشته ای یک سری دانشجور=هر دانشجو یک سری اظلاهات فذدی و اینکه هذ داشنجو یک نمره ای هم داره =دسترسی هم بعد بهش بده 

var University={
    name:"Esfahan University",
    buildingNumbers:"6",
    sate_university:true,
    world_rank:"334",
    iran_rank:"2",
    UniversityEmail:"Esfahan_University@gmail.com",
    owner:"government",
    location:{
        country:"iran",
        city:"esfahan",
        location:"Esfahan Azadi square Daneshgah street"
    },
    contactNumber:[
        {department:"information",
         number:"031359285",
         isActive:true,
         workingHours:"8-14"
        },
        {department:"management",
         number:"031369175",
         isActive:true,
         workingHours:"8-14"
        },
        {department:"sign-in",
         number:"03137592",
         isActive:false,
         workingHours:"8-14"
        },
        {department:"security",
         number:"031395718",
         isActive:true,
         workingHours:"8-14"
        },
        {department:"classes",
         number:"031316568",
         isActive:true,
         workingHours:"8-14"
        },
    ],
    faculties:{
        faclty_of_computer_engineering_and_it:{
            name:"faclty of computer engineering & it",
            id:"001",
            buildingNumber:"6",
            floor:"2",
            classNumber:"26",
            dean:{
                name:"dr.ahmadi",
                email:"dr.ahmadi@gmail.com",
                idCart:"1273492759",
                number:"09131117592",
                age:"59"
            },
            courses:[
                {
                    name:"introduction to programing",
                    id:"101",
                    classNumber:"1",
                    workinDays:"1-3-5",
                    teacher:{
                        name:"dr.ahmadi",
                        email:"dr.ahmadi@gmail.com",
                        idCart:"1273492759",
                        number:"09131117592",
                        age:"59"
                    },
                    students:[
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"ali",
                            idCart:"0017862359",
                            lastName:"taji",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        }
                    ]
                },
                {
                    name:"data & algorithmes",
                    id:"102",
                    classNumber:"2",
                    workinDays:"1-4-5",
                    teacher:{
                        name:"dr.safaee",
                        email:"dr.safaee@gmail.com",
                        idCart:"12736589759",
                        number:"09139917592",
                        age:"39"
                    },
                    students:[
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"ali",
                            idCart:"0017862359",
                            lastName:"taji",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        }
                    ]
                },
                {
                    name:"database systems",
                    id:"103",
                    classNumber:"3",
                    workinDays:"3-4",
                    teacher:{
                        name:"dr.mamoud",
                        email:"dr.mahmoud@gmail.com",
                        idCart:"12123589759",
                        number:"09379912592",
                        age:"45"
                    },
                    students:[
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        }
                    ]
                },
                {
                    name:"operating systems",
                    id:"104",
                    classNumber:"4",
                    workinDays:"1-2-6",
                    teacher:{
                        name:"dr.safaee",
                        email:"dr.safaee@gmail.com",
                        idCart:"12736589759",
                        number:"09139917592",
                        age:"59"
                    },
                    students:[
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        }
                    ]
                }

            ]
        },
        faculty_of_mechanical_engineering:{
            name:"faculty of mechanical engineering",
            id:"002",
            buildingNumber:"3",
            floor:"4",
            classNumber:"15",
            dean:{
                name:"dr.mahamadi",
                email:"dr.mohamadi@gmail.com",
                idCart:"1275729562",
                number:"09132225937",
                age:"48"
            },
            courses:[
                {
                    name:"staics & dynamics",
                    id:"201",
                    classNumber:"6",
                    workinDays:"1-3-5",
                    teacher:{
                        name:"dr.mamoud",
                        email:"dr.mahmoud@gmail.com",
                        idCart:"12123589759",
                        number:"09379912592",
                        age:"45"
                    },
                    students:[
                        {
                            name:"mehdi",
                            idCart:"1279234727",
                            lastName:"talesh",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"zahra",
                            idCart:"1271114427",
                            lastName:"sokranii",
                            score:"a",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"masome",
                            idCart:"0019098527",
                            lastName:"maryamy",
                            score:"d",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"127909543",
                            lastName:"khodami",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"maryam",
                            idCart:"7659098427",
                            lastName:"abbaz",
                            score:"c",
                            from:"iran",
                            gender:"female"
                        },
                    ]
                },
                {
                    name:"thermodynamics",
                    id:"202",
                    classNumber:"7",
                    workinDays:"1-4-5",
                    teacher:{
                        name:"dr.mani",
                        email:"dr.mani@gmail.com",
                        idCart:"121764213457",
                        number:"09387236743",
                        age:"34"
                    },
                    students:[
                        {
                            name:"mehdi",
                            idCart:"1279234727",
                            lastName:"talesh",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"zahra",
                            idCart:"1271114427",
                            lastName:"sokranii",
                            score:"a",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"127909543",
                            lastName:"khodami",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"maryam",
                            idCart:"7659098427",
                            lastName:"abbaz",
                            score:"c",
                            from:"iran",
                            gender:"female"
                        }
                    ]
                },
                {
                    name:"fluid mechanics",
                    id:"203",
                    classNumber:"8",
                    workinDays:"3-4",
                    teacher:false,
                    students:[
                        {
                            name:"mehdi",
                            idCart:"1279234727",
                            lastName:"talesh",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"zahra",
                            idCart:"1271114427",
                            lastName:"sokranii",
                            score:"a",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"masome",
                            idCart:"0019098527",
                            lastName:"maryamy",
                            score:"d",
                            from:"iran",
                            gender:"female"
                        }
                    ]
                },
                {
                    name:"heat yransfer",
                    id:"204",
                    classNumber:"9",
                    workinDays:"1-2-6",
                    teacher:{
                        name:"dr.mayam",
                        email:"dr.maryam@gmail.com",
                        idCart:"2343589759",
                        number:"0937945582",
                        age:"29"
                    },
                    students:[
                        {
                            name:"masome",
                            idCart:"0019098527",
                            lastName:"maryamy",
                            score:"d",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"ali",
                            idCart:"0017862359",
                            lastName:"taji",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"mahamad",
                            idCart:"127909543",
                            lastName:"khodami",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"maryam",
                            idCart:"7659098427",
                            lastName:"abbaz",
                            score:"c",
                            from:"iran",
                            gender:"female"
                        }
                    ]
                }

            ]
        },
        faculty_of_basic_sciences:{
            name:"faculty of basic sciences",
            id:"003",
            buildingNumber:"6",
            floor:"1",
            classNumber:"4",
            dean:{
                name:"dr.karimi",
                email:"dr.karimi@gmail.com",
                idCart:"127568374",
                number:"09133331747",
                age:"53"
            },
            courses:[
                {
                    name:"calculus I",
                    id:"301",
                    classNumber:"10",
                    workinDays:"1-3-5",
                    teacher:{
                        name:"dr.mamoud",
                        email:"dr.mahmoud@gmail.com",
                        idCart:"12123589759",
                        number:"09379912592",
                        age:"45"
                    },
                    students:[
                        {
                            name:"mehdi",
                            idCart:"1279234727",
                            lastName:"talesh",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"ali",
                            idCart:"0017862359",
                            lastName:"taji",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"zahra",
                            idCart:"1271114427",
                            lastName:"sokranii",
                            score:"a",
                            from:"iran",
                            gender:"female"
                        }
                    ]
                },
                {
                    name:"calculus II",
                    id:"302",
                    classNumber:"11",
                    workinDays:"1-4-5",
                    teacher:{
                        name:"dr.mamoud",
                        email:"dr.mahmoud@gmail.com",
                        idCart:"12123589759",
                        number:"09379912592",
                        age:"45"
                    },
                    students:[
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                    ]
                },
                {
                    name:"linear algebra I",
                    id:"303",
                    classNumber:"12",
                    workinDays:"3-4",
                    teacher:{
                        name:"dr.mani",
                        email:"dr.mani@gmail.com",
                        idCart:"121764213457",
                        number:"09387236743",
                        age:"34"
                    },
                    students:[
                        {
                            name:"mehdi",
                            idCart:"1279234727",
                            lastName:"talesh",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"zahra",
                            idCart:"1271114427",
                            lastName:"sokranii",
                            score:"a",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                    ]
                },
                {
                    name:"linear algebra I",
                    id:"304",
                    classNumber:"13",
                    workinDays:"1-2-6",
                    teacher:{
                        name:"dr.mayam",
                        email:"dr.maryam@gmail.com",
                        idCart:"2343589759",
                        number:"0937945582",
                        age:"29"
                    },
                    students:[
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"ali",
                            idCart:"0017862359",
                            lastName:"taji",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"masome",
                            idCart:"0019098527",
                            lastName:"maryamy",
                            score:"d",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"127909543",
                            lastName:"khodami",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        }
                    ]
                }

            ]
        },
        faculty_of_engineering:{
            name:"faculty of_mechanical engineering",
            id:"004",
            buildingNumber:"6",
            floor:"2",
            classNumber:"28",
            dean:{
                name:"dr.emani",
                email:"dr.emani@gmail.com",
                idCart:"1282139473",
                number:"09134446767",
                age:"30"
            },
            courses:[
                {
                    name:"general psychology",
                    id:"401",
                    classNumber:"14",
                    workinDays:"1-3-5",
                    teacher:{
                        name:"dr.safaee",
                        email:"dr.safaee@gmail.com",
                        idCart:"12736589759",
                        number:"09139917592",
                        age:"59"
                    },
                    students:[
                        {
                            name:"mehdi",
                            idCart:"1279234727",
                            lastName:"talesh",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"zahra",
                            idCart:"1271114427",
                            lastName:"sokranii",
                            score:"a",
                            from:"iran",
                            gender:"female"
                        },
                    ]
                },
                {
                    name:"general development",
                    id:"402",
                    classNumber:"15",
                    workinDays:"1-4-5",
                    teacher:{
                        name:"dr.mamoud",
                        email:"dr.mahmoud@gmail.com",
                        idCart:"12123589759",
                        number:"09379912592",
                        age:"45"
                    },
                    students:[
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                    ]
                },
                {
                    name:"general methods",
                    id:"403",
                    classNumber:"16",
                    workinDays:"3-4",
                    teacher:{
                        name:"dr.mamoud",
                        email:"dr.mahmoud@gmail.com",
                        idCart:"12123589759",
                        number:"09379912592",
                        age:"45"
                    },
                    students:[
                        {
                            name:"masome",
                            idCart:"0019098527",
                            lastName:"maryamy",
                            score:"d",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"127909543",
                            lastName:"khodami",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"alex",
                            idCart:"0043892828",
                            lastName:"fochini",
                            score:"a+",
                            from:"america",
                            gender:"male"
                        },
                        {
                            name:"fateme",
                            idCart:"1815436819",
                            lastName:"shahmoradi",
                            score:"b+",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"ali",
                            idCart:"0017862359",
                            lastName:"taji",
                            score:"f+",
                            from:"iran",
                            gender:"male"
                        }
                    ]
                },
                {
                    name:"general literature",
                    id:"404",
                    classNumber:"17",
                    workinDays:"1-2-6",
                    teacher:{
                        name:"dr.safaee",
                        email:"dr.safaee@gmail.com",
                        idCart:"12736589759",
                        number:"09139917592",
                        age:"59"
                    },
                    students:[
                        {
                            name:"aria",
                            idCart:"1275729562",
                            lastName:"esmaeilian",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"sara",
                            idCart:"127947294",
                            lastName:"moradi",
                            score:"a",
                            from:"america",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"1279098427",
                            lastName:"sokri",
                            score:"c",
                            from:"iran",
                            gender:"male"
                        },
                        {
                            name:"masome",
                            idCart:"0019098527",
                            lastName:"maryamy",
                            score:"d",
                            from:"iran",
                            gender:"female"
                        },
                        {
                            name:"mahamad",
                            idCart:"127909543",
                            lastName:"khodami",
                            score:"a+",
                            from:"iran",
                            gender:"male"
                        },
                    ]
                }

            ]
        },
    }
}
console.log(University.faculties.faculty_of_mechanical_engineering.dean.idCart);
console.log(University.faculties.faculty_of_mechanical_engineering.courses[1].teacher.number);
console.log(University.faculties.faculty_of_mechanical_engineering.courses[1].students[3].score);
console.log(University.faculties.faculty_of_mechanical_engineering.courses[2].students[2].gender);
console.log(University.faculties.faculty_of_mechanical_engineering.courses[0].students[1].name);